modLoader="javafml"
loaderVersion="[40,)"
license="LGPL-3.0"
[[mods]]
modId="wastelanddisease"
version="${file.jarVersion}"
displayName="Wasteland Disease"
logoFile="modicon.png"
credits="Thanks DrViruss for the advice."
authors="Techeart"
description='''Do you like to spend time outdoors? ยง4Forget it!'''
[[dependencies.wastelanddisease]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wastelanddisease]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
