modLoader="javafml"
loaderVersion="[37,)"
license="LGPL-3.0"
[[mods]]
modId="thrad"
version="1.17.1-0.1.0"
displayName="Wasteland Disease"
logoFile="modicon.png"
credits="Thanks DrViruss for the advice."
authors="Techeart"
description='''Do you like to spend time outdoors? ยง4Forget it!'''
[[dependencies.thrad]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thrad]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
